import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/types/index.ts",
    "src/crypto/index.ts",
    "src/test/index.ts",
    "src/client/index.ts",
    "src/client/react/index.ts",
    "src/client/vue/index.ts",
    "src/client/svelte/index.ts",
    "src/client/angular/index.ts",
    "src/client/nextjs/index.ts",
    "src/adapters/prisma/index.ts",
    "src/adapters/drizzle/index.ts",
    "src/adapters/kysely/index.ts",
    "src/adapters/mongoose/index.ts",
    "src/adapters/memory/index.ts",
    "src/api/call.ts",
    "src/api/index.ts",
    "src/api/to-marketing-endpoints.ts",
    "src/frameworks/express/index.ts",
    "src/frameworks/fastify/index.ts",
    "src/frameworks/hono/index.ts",
    "src/frameworks/nestjs/index.ts",
    "src/frameworks/nextjs/index.ts",
    "src/frameworks/sveltekit/index.ts",
    "src/email-providers/resend/index.ts",
    "src/email-providers/sendgrid/index.ts",
    "src/email-providers/mailgun/index.ts",
    "src/email-providers/postmark/index.ts",
    "src/sms-providers/twilio/index.ts",
    "src/analytics-providers/google-analytics/index.ts",
    "src/analytics-providers/mixpanel/index.ts",
    "src/plugins/campaigns/index.ts",
    "src/plugins/automation/index.ts",
    "src/plugins/segmentation/index.ts",
    "src/plugins/ab-testing/index.ts",
    "src/plugins/personalization/index.ts",
    "src/plugins/lead-scoring/index.ts",
    "src/plugins/attribution/index.ts",
    "src/plugins/webhooks/index.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  clean: true,
  sourcemap: true,
  minify: false,
  target: "node18",
  external: [
    "react",
    "vue",
    "svelte",
    "@angular/core",
    "next",
    "express",
    "fastify",
    "hono",
    "@nestjs/common",
    "prisma",
    "drizzle-orm",
    "kysely",
    "mongoose",
  ],
});
