import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/api/call.ts",
    "src/api/index.ts",
    "src/client/index.ts",
    "src/crypto/index.ts",
    "src/test/index.ts",
    "src/types/index.ts",
    "src/adapters/memory/index.ts",
    "src/client/react/index.ts",
    "src/integrations/nextjs/index.tsx",
  ],
  format: ["cjs", "esm"],
  dts: true,
  clean: true,
  sourcemap: true,
  minify: false,
  target: "node18",
  external: [
    "react",
    "vue",
    "svelte",
    "@angular/core",
    "next",
    "express",
    "fastify",
    "hono",
    "@nestjs/common",
    "prisma",
    "drizzle-orm",
    "kysely",
    "mongoose",
  ],
});
